### ISSUE TITLE
Design tokens / Dark mode

### ISSUE THREAD

**Issue by techniq** [techniq/svelte-ux#66]
Use CSS variables and/or extend [Tailwind color palette](https://tailwindcss.com/docs/customizing-colors#using-css-variables) to easily support dark mode, and provide more flexibility for styling customization beyond accent color and theme support (per-component classes)

[Design token comparison](https://docs.google.com/spreadsheets/d/1cUhOldinoh-t_0oFimtHOsdPFr_Z0IwopGUCL78Y0r0/edit#gid=0) spreadsheet

---

## Thoughts / Questions
- What to call text/content on a color?
  - `COLOR-content` (daisy), `COLOR-foreground` (shadcn), `on-COLOR` (skeleton), `COLOR-text` (~open props)
- What to call main background?
  - `base-100` (daisy), `background` (shadcn)
- What to call main text color
  - `base-content` (daisy), `foreground` (shadcn), `font-color-base` (skeleton), `text-1` (open props)
- What color space to use (hsl, rgb, oklch)?
  - rgb()
    - Most universal, used by Tailwind, Skeleton
  - hsl()
    - Probably the most developer friendly ATM
    - Used by shadcn
  - oklch()
    - Only [supported](https://caniuse.com/mdn-css_types_color_oklch) in last 1-2 years (Safari 15.4+).
    - Supports P3 colors
    - Used by Daisy UI
- Additional properties like general borders, roundness, etc
- Should use explicit colors (most) or shades (skeleton, next-ui)
  - Shades support nice pairings ([skeleton](https://www.skeleton.dev/docs/tokens#color-pairing-chart)) but explicit are easier to setup (and more generally used)
  - Shades allow for darker shades without having to use [color-mix()](https://caniuse.com/mdn-css_types_color_color-mix), which only has support this year (Safari 16.2, Chrome 111)
- Ability to reuse themes
- Should hovered filled buttons get more transparent, lighter, darker?
  - Currently getting darker
  - Using `color-mix()` works for any of these, but only supported in last 8-12 months?  Progressive enhancement, or find way to fallback to using opacity
    - Tailwind `@supports` via [arbitrary variant](https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants) - [@supports(display:grid)]:grid
- Should each component expose their own colors (like Button for `--bg-color`, `--text-color`, `--border-color`, etc) or is setting `--ux-primary` / `--ux-primary-content` sufficient
  - Would be a descent lift, but maybe worth it
  - Some components already expose CSS variables for styling (ProgressBar as `--color`, Field/TextField).  Switch current uses explicit `bg-*`, `border-*` but might be worth changing
- When should we use `primary`, `secondary`, `accent`, `neutral`, etc?  Always primary unless explicit?
---

## TODO
- [x] Determine tokens (colors, borders, etc)
- [x] Update all components to use tokens
- [x] Add dark mode (and maybe other themes)
- [x] Ability to switch themes
  - https://github.com/saadeghi/theme-change
  - https://github.com/huntabyte/mode-watcher
  - https://www.skeleton.dev/utilities/lightswitches
  - https://flowbite.com/docs/customize/dark-mode/#dark-mode-switcher
  - [x] Extract Theme selector as component (to be used in other projects)
- [x] Consider renaming current `settings: {{ theme: ... }}` to `classes` or `overrides`
- [x] Support defining theme in tailwind config
  - daisy ui [example](https://play.tailwindcss.com/TmSTdx3aP3?file=config)
- [x] Add examples for mappings existing themes
  - [x] Daisy UI
  - [x] Skeleton
  - [x] Basic tailwind colors
- [x] Debate on using `bg-mix-[theme(colors.primary)/+90]` instead of `bg-primary-50` (and `+80` / `-100`)
  - Added lighter/darker shades for all theme colors (ex. `colors.primary-600`)
- [x] Support changing color space (`oklch`, `hsl`, `rgb`)
- [x] Remove usage of old CSS variables `var(--color-blue-100)`, etc (tableBackground, etc)
- [x] Color replacement
  - [x] Replace `bg-white` with `bg-surface-100` (or similar)
  - [x] Replace `text-black` with `text-surface-content` (or similar)
  - [x] Replace `bg-black` (and `bg-black/5`, `bg-black/50`, etc) possibly with `bg-surface-content`
  - [x] Replace `border-*` colors
  - [x] Replace `*-black-*`
  - [x] Replace `*-white-*`
  - [x] Replace `*-gray-*`
  - [x] Replace `#ddd`
  - [x] All old color references (look for `-500`, etc).  Example: Table's `var(--color-blue-500)`
- [x] Globally change the default `border` color to `border-surface-300`
- [x] Rename `--ux-{COLOR}` to `--color-{COLOR}` (after current `--color*` variables are evaluated
- [x] Add more colors
  - [x] accent
  - [x] neutral
- [x] Rename `error` color to `danger`
- [x] Add borders (and other styles) to config
- [ ] Refine/remove default Drawer/Dialog action styles
- [x] Update mdsvex code background (like `<Code>`/`<Preview>`)
- [x] Fix tailwind prose classes (markdown pages)
- [ ] Consider setting `<input>` default background with global styles (same for scrollbars - #122)
- [x] Improve handling of `system` color scheme / theme in `ThemeButton`
- [x] Remove `daisyui` required dependency (see LayerChart [issue](https://github.com/techniq/layerchart/issues/81))
  - Possible become separate package
  - Maybe just generate `theme.json` file that can be easily referenced
- [x] Add default `light` / `dark` themes
- [x] Update templates
- [x] Update Customization guide

**Comment by techniq** [comment]
/*
 * Open Props (https://open-props.style/#colors)
 */

/*
--brand: var(--brand-dark);
--text-1: var(--text-1-dark);
--text-2: var(--text-2-dark);
--surface-1: var(--surface-1-dark);
--surface-2: var(--surface-2-dark);
--surface-3: var(--surface-3-dark);
--surface-4: var(--surface-4-dark);
--shadow-{1-6}
--inner-shadow-{0-4}
--surface-shadow: var(--surface-shadow-dark);
--shadow-strength: var(--shadow-strength-dark);
--font-size-{00-8}
--font-size-fluid-{0-3}
--font-weight-{1-9}
--font-letterspacing-{0-7}
--font-lineheight-{00-5}
*/

/************************************************/

/*
 * shadcn/ui (https://ui.shadcn.com/docs/theming)
 */

/*
  Default background color of <body />...etc
  --background: 0 0% 100%;
  --foreground: 222.2 47.4% 11.2%;

  Muted backgrounds such as <TabsList />, <Skeleton /> and <Switch />
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;

  Background color for <Card />
  --card: 0 0% 100%;
  --card-foreground: 222.2 47.4% 11.2%;

  Background color for popovers such as <DropdownMenu />, <HoverCard />, <Popover />
  --popover: 0 0% 100%;
  --popover-foreground: 222.2 47.4% 11.2%;

  Default border color
  --border: 214.3 31.8% 91.4%;

  Border color for inputs such as <Input />, <Select />, <Textarea />
  --input: 214.3 31.8% 91.4%;

  Primary colors for <Button />
  --primary: 222.2 47.4% 11.2%;
  --primary-foreground: 210 40% 98%;

  Secondary colors for <Button />
  --secondary: 210 40% 96.1%;
  --secondary-foreground: 222.2 47.4% 11.2%;

  Used for accents such as hover effects on <DropdownMenuItem>, <SelectItem>...etc
  --accent: 210 40% 96.1%;
  --accent-foreground: 222.2 47.4% 11.2%;

  Used for destructive actions such as <Button variant="destructive">
  --destructive: 0 100% 50%;
  --destructive-foreground: 210 40% 98%;

  Used for focus ring
  --ring: 215 20.2% 65.1%;

  Border radius for card, input and buttons
  --radius: 0.5rem;
*/

/*
 * Daisy UI (https://daisyui.com/docs/colors/)
 */

/*
primary
Primary color	required	Class name: bg-primary
CSS variable: hsl(var(--p))

primary-focus
Primary color when focused	optional
Will be a darker tone of primary if not specified	Class name: bg-primary-focus
CSS variable: hsl(var(--pf))

primary-content
Foreground content color to use on primary color	optional
Will be a readable tone of primary if not specified	Class name: bg-primary-content
CSS variable: hsl(var(--pc))

secondary
Secondary color	required	Class name: bg-secondary
CSS variable: hsl(var(--s))

secondary-focus
Secondary color when focused	optional
Will be a darker tone of secondary if not specified	Class name: bg-secondary-focus
CSS variable: hsl(var(--sf))

secondary-content
Foreground content color to use on secondary color	optional
Will be a readable tone of secondary if not specified	Class name: bg-secondary-content
CSS variable: hsl(var(--sc))

accent
Accent color	required	Class name: bg-accent
CSS variable: hsl(var(--a))

accent-focus
Accent color when focused	optional
Will be a darker tone of accent if not specified	Class name: bg-accent-focus
CSS variable: hsl(var(--af))

accent-content
Foreground content color to use on accent color	optional
Will be a readable tone of accent if not specified	Class name: bg-accent-content
CSS variable: hsl(var(--ac))

neutral
Neutral color	required	Class name: bg-neutral
CSS variable: hsl(var(--n))

neutral-focus
Neutral color when focused	optional
Will be a darker tone of neutral if not specified	Class name: bg-neutral-focus
CSS variable: hsl(var(--nf))

neutral-content
Foreground content color to use on neutral color	optional
Will be a readable tone of neutral if not specified	Class name: bg-neutral-content
CSS variable: hsl(var(--nc))

base-100
Base color of page, used for blank backgrounds	required	Class name: bg-base-100
CSS variable: hsl(var(--b1))

base-200
Base color, a little darker	optional
Will be a darker tone of base-100 if not specified	Class name: bg-base-200
CSS variable: hsl(var(--b2))

base-300
Base color, even more darker	optional
Will be a darker tone of base-200 if not specified	Class name: bg-base-300
CSS variable: hsl(var(--b3))

base-content
Foreground content color to use on base color	optional
Will be a readable tone of base-100 if not specified	Class name: bg-base-content
CSS variable: hsl(var(--bc))

info
Info color	optional
Will be a default blue color if not specified	Class name: bg-info
CSS variable: hsl(var(--in))

info-content
Foreground content color to use on info color	optional
Will be a readable tone of info if not specified	Class name: bg-info-content
CSS variable: hsl(var(--inc))

success
Success color	optional
Will be a default green color if not specified	Class name: bg-success
CSS variable: hsl(var(--su))

success-content
Foreground content color to use on success color	optional
Will be a readable tone of success if not specified	Class name: bg-success-content
CSS variable: hsl(var(--suc))

warning
Warning color	optional
Will be a default orange color if not specified	Class name: bg-warning
CSS variable: hsl(var(--wa))

warning-content
Foreground content color to use on warning color	optional
Will be a readable tone of warning if not specified	Class name: bg-warning-content
CSS variable: hsl(var(--wac))

error
Error color	optional
Will be a default red color if not specified	Class name: bg-error
CSS variable: hsl(var(--er))

error-content
Foreground content color to use on error color	optional
Will be a readable tone of error if not specified	Class name: bg-error-content
CSS variable: hsl(var(--erc))
*/

/*
 * React Aria
 */

/*
--border-color: var(--spectrum-alias-border-color);
--border-color-pressed: var(--spectrum-alias-border-color-down);
--border-color-disabled: var(--spectrum-alias-border-color-disabled);
--background-color: var(--spectrum-global-color-gray-50);
--background-color-pressed: var(--spectrum-global-color-gray-100);
--text-color: var(--spectrum-alias-text-color);
--text-color-disabled: var(--spectrum-alias-text-color-disabled);
--focus-ring-color: slateblue;
*/

**Comment by techniq** [comment]
- Skeleton UI
  - https://www.skeleton.dev/docs/colors
  - https://www.skeleton.dev/docs/tokens
  - Multiple shades per color
    - `--color-primary-{50-900}`
    - `--color-secondary-{50-900}`
    - `--color-tertiary-{50-900}`
    - `--color-success-{50-900}`
    - `--color-warning-{50-900}`
    - `--color-error-{50-900}`
    - `--color-surface-{50-900}`
    - `--theme-border-base`
    - `--theme-rounded-container`
    - `--theme-rounded-base`
    - `--theme-font-color-base`
    - `--theme-font-color-dark`
    - `--theme-font-family-base`
    - `--theme-font-family-heading`
    -  `--on-{color}`
- shadcn/ui
  - https://ui.shadcn.com/docs/theming
  - Colors
    - `--primary{-foreground}`
    - `--secondary{-foreground}`
    - `--accent{-foreground}`
    - `--muted{-foreground}`
    - `--destructive{-foreground}`
    - `--popover{-foreground}`
    - `--card{-foreground}`
  - `--input`
  - `--border`
  - `--radius`
  - `--ring`
- Open props
  - https://open-props.style/#colors
  - [Color schemes](https://codepen.io/argyleink/pen/XWaYyWe)
  - [Light / Dark button example](https://codepen.io/argyleink/pen/xxQmqOY)
  - [Adaptive Ghost buttons example](https://codepen.io/argyleink/pen/powMQgx)
  - [Pagination example](https://codepen.io/argyleink/pen/QWMreXR)
  - [Normalized demo page](https://codepen.io/argyleink/pen/KKvRORE)
  - `--brand`
  - `--text-{1-2}`
  - `--surface-{1-4}`
  - `--shadow-{1-6}`
  - `--inner-shadow-{0-4}`
  - `--surface-shadow`
  - `--shadow-stregth`
  - `--font-size-{0-8}`
  - `--font-size-fluid-{0-3}`
  - `--font-weight-{1-9}`
  - `--font-letterspacing-{0-7}`
  - `--font-lineheight-{0-5}`
- Daisy UI
  - https://daisyui.com/docs/colors/
  - `--primary{-content}`
  - `--secondary{-content}`
  - `--accent{-content}`
  - `--neutral{-content}`
  - `--info{-content}`
  - `--success{-content}`
  - `--warning{-content}`
  - `--error{-content}`
  - `--base-{100-300,content}`
- tremor
  - https://www.tremor.so/docs/getting-started/theming
  - `--brand{-faint,muted,subtle,DEFAULT,emphasis,inverted}`
  - `--background{-muted,subtle,DEFAULT,emphasis}`
  - `--border`
  - `--ring`
  - `--content{-subtle,DEFAULT,emphasis,strong,inverted}`
- Next UI
  - https://nextui.org/docs/customization/theme
  - HSL
  - base
  - `--foreground{-50-900}`
  - `--background{-50-900}`
  - `--divider{-50-900}`
  - `--overlay{-50-900}`
  - `--focus{-50-900}`
  - `--content1{-50-900}`
  - `--primary{-50-900}`
  - `--secondary{-50-900}`
  - `--success{-50-900}`
  - `--warning{-50-900}`
  - `--danger{-50-900}`
  - ...
- Colors
  -  https://translate-tailwind-colors.vercel.app/

**Comment by techniq** [comment]
Shipped!
